import { DrugInteractionRule } from './types';

export const DRUG_INTERACTIONS_DATA: DrugInteractionRule[] = [
  // Cardiovascular & Anticoagulants
  {
    drugA: 'Warfarin',
    drugB: 'Aspirin',
    genericA: 'warfarin sodium',
    genericB: 'acetylsalicylic acid',
    severity: 'MAJOR',
    mechanism: 'Additive antiplatelet effect of aspirin combined with anticoagulant effect of warfarin significantly increases risk of major gastrointestinal and intracranial hemorrhage.',
    clinicalEffect: 'Synergistic bleeding risk, prolonged PT/INR, occult GI blood loss.',
    management: 'Avoid concurrent use unless strictly indicated (e.g. mechanical heart valves with acute coronary syndrome). Monitor INR closely and co-prescribe gastroprotection (PPI).',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Clopidogrel (if antiplatelet indicated without NSAID effect)', 'Direct oral anticoagulants (Apixaban, Rivaroxaban) with tailored antiplatelet therapy'],
  },
  {
    drugA: 'Warfarin',
    drugB: 'Amiodarone',
    genericA: 'warfarin sodium',
    genericB: 'amiodarone hydrochloride',
    severity: 'MAJOR',
    mechanism: 'Amiodarone is a potent inhibitor of CYP2C9 and CYP3A4, markedly decreasing warfarin metabolism and leading to supratherapeutic INR levels.',
    clinicalEffect: 'Severe hypoprothrombinemia, life-threatening internal bleeding.',
    management: 'Reduce warfarin dose by 33% to 50% upon starting amiodarone. Monitor INR weekly for the first 6 weeks.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Dronedarone (with caution)', 'Sotalol for rhythm control'],
  },
  {
    drugA: 'Warfarin',
    drugB: 'Ciprofloxacin',
    genericA: 'warfarin sodium',
    genericB: 'ciprofloxacin',
    severity: 'MAJOR',
    mechanism: 'Fluoroquinolones inhibit CYP1A2 and alter gut flora producing vitamin K2, enhancing warfarin anticoagulant potency.',
    clinicalEffect: 'Elevated INR within 24 to 72 hours, bleeding diathesis.',
    management: 'Check INR 48-72h after initiating fluoroquinolone. Consider pre-emptive warfarin dose reduction of 20-30%.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Beta-lactams (Amoxicillin/Clavulanate, Cephalexin)', 'Macrolides with caution'],
  },
  {
    drugA: 'Warfarin',
    drugB: 'Fluconazole',
    genericA: 'warfarin sodium',
    genericB: 'fluconazole',
    severity: 'CONTRAINDICATED',
    mechanism: 'Potent competitive inhibition of CYP2C9 by fluconazole reduces clearance of active S-warfarin isomer by up to 70%.',
    clinicalEffect: 'Dangerous INR spikes (>8.0), gross hematuria, retroperitoneal bleeding.',
    management: 'Contraindicated for unmonitored therapy. If unavoidable, reduce warfarin dose by 50% and monitor INR every 2 days.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Topical antifungals for localized infection', 'Nystatin oral suspension'],
  },
  {
    drugA: 'Simvastatin',
    drugB: 'Amlodipine',
    genericA: 'simvastatin',
    genericB: 'amlodipine besylate',
    severity: 'MODERATE',
    mechanism: 'Amlodipine inhibits CYP3A4-mediated first-pass metabolism of simvastatin, increasing simvastatin systemic exposure by approximately 77%.',
    clinicalEffect: 'Increased incidence of statin-induced myopathy, elevated creatine kinase (CK), rhabdomyolysis.',
    management: 'Limit simvastatin dose to a maximum of 20 mg daily when co-administered with amlodipine, or switch to Rosuvastatin/Pravastatin.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Atorvastatin (up to 40 mg)', 'Rosuvastatin (10-20 mg)', 'Pravastatin (40 mg)'],
  },
  {
    drugA: 'Simvastatin',
    drugB: 'Clarithromycin',
    genericA: 'simvastatin',
    genericB: 'clarithromycin',
    severity: 'CONTRAINDICATED',
    mechanism: 'Clarithromycin is a strong mechanism-based inhibitor of CYP3A4, causing up to 10-fold increase in simvastatin AUC.',
    clinicalEffect: 'Acute rhabdomyolysis, acute tubular necrosis, renal failure.',
    management: 'Temporarily suspend simvastatin therapy during course of clarithromycin, or choose non-CYP3A4 macrolide/antibiotic.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Azithromycin (weaker CYP3A4 inhibition)', 'Doxycycline', 'Amoxicillin'],
  },
  {
    drugA: 'Lisinopril',
    drugB: 'Spironolactone',
    genericA: 'lisinopril',
    genericB: 'spironolactone',
    severity: 'MAJOR',
    mechanism: 'Combined aldosterone inhibition and reduced renal potassium excretion by ACE inhibitors and mineralocorticoid receptor antagonists.',
    clinicalEffect: 'Severe hyperkalemia (>6.0 mmol/L), cardiac conduction abnormalities, ventricular arrhythmias, asystole.',
    management: 'Monitor serum potassium and renal function baseline, at 1 week, 4 weeks, and periodically. Avoid potassium supplements.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Thiazide diuretic if hyperkalemia risk is excessive', 'Eplerenone with strict monitoring'],
  },
  {
    drugA: 'Lisinopril',
    drugB: 'Losartan',
    genericA: 'lisinopril',
    genericB: 'losartan potassium',
    severity: 'CONTRAINDICATED',
    mechanism: 'Dual renin-angiotensin-aldosterone system (RAAS) blockade without additive clinical benefit in cardiovascular outcomes.',
    clinicalEffect: 'Increased rates of acute kidney injury (AKI), severe hypotension, hyperkalemia.',
    management: 'Avoid dual RAAS blockade. Discontinue one agent.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Combine ACE inhibitor or ARB with Calcium Channel Blocker or Thiazide diuretic instead'],
  },
  {
    drugA: 'Digoxin',
    drugB: 'Amiodarone',
    genericA: 'digoxin',
    genericB: 'amiodarone hydrochloride',
    severity: 'MAJOR',
    mechanism: 'Amiodarone inhibits P-glycoprotein (P-gp) efflux transporter and renal tubular secretion of digoxin.',
    clinicalEffect: 'Doubling of serum digoxin concentration, visual halos, nausea, heart block, life-threatening ventricular tachyarrhythmias.',
    management: 'Reduce digoxin dose by 50% prior to starting amiodarone. Measure serum digoxin level within 7 to 10 days.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Beta-blockers (Metoprolol succinate, Bisoprolol)', 'Non-dihydropyridine CCBs if no systolic dysfunction'],
  },
  {
    drugA: 'Digoxin',
    drugB: 'Verapamil',
    genericA: 'digoxin',
    genericB: 'verapamil hydrochloride',
    severity: 'MAJOR',
    mechanism: 'Verapamil inhibits P-gp mediated elimination and has additive negative dromotropic effects at the AV node.',
    clinicalEffect: 'Digoxin toxicity and complete AV nodal block.',
    management: 'Reduce digoxin dose by 30-50% and obtain ECG rhythm strip.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Diltiazem (lower P-gp inhibition)', 'Selective beta-1 blockers'],
  },
  {
    drugA: 'Clopidogrel',
    drugB: 'Omeprazole',
    genericA: 'clopidogrel bisulfate',
    genericB: 'omeprazole',
    severity: 'MAJOR',
    mechanism: 'Omeprazole competitively inhibits CYP2C19, preventing bioactivation of clopidogrel prodrug into its active thiol metabolite.',
    clinicalEffect: 'Reduced antiplatelet inhibition, increased risk of stent thrombosis and recurrent myocardial infarction.',
    management: 'Avoid omeprazole/esomeprazole with clopidogrel. Use Pantoprazole or H2-receptor antagonists (Famotidine).',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Pantoprazole (minimal CYP2C19 inhibition)', 'Famotidine', 'Rabeprazole'],
  },
  {
    drugA: 'Metoprolol',
    drugB: 'Fluoxetine',
    genericA: 'metoprolol tartrate/succinate',
    genericB: 'fluoxetine hydrochloride',
    severity: 'MODERATE',
    mechanism: 'Fluoxetine is a potent inhibitor of CYP2D6, the primary clearance enzyme for lipophilic beta-blockers.',
    clinicalEffect: 'Elevated metoprolol plasma levels, severe symptomatic bradycardia, hypotension, lethargy.',
    management: 'Consider dose reduction of metoprolol or switch to atenolol/bisoprolol/nadolol (renally eliminated).',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Atenolol', 'Bisoprolol', 'Sertraline or Citalopram for depression'],
  },

  // Psychiatric, Neurological & Sedatives
  {
    drugA: 'Sertraline',
    drugB: 'Tramadol',
    genericA: 'sertraline hydrochloride',
    genericB: 'tramadol hydrochloride',
    severity: 'MAJOR',
    mechanism: 'Combined serotonin reuptake inhibition by SSRI and tramadol (which also enhances serotonin release and inhibits reuptake).',
    clinicalEffect: 'Serotonin syndrome: agitation, tremor, hyperreflexia, hyperthermia, clonus, delirium, seizures.',
    management: 'Avoid concurrent therapy. If opioid analgesic required, choose non-serotonergic agent like morphine, oxycodone, or acetaminophen.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Acetaminophen', 'Oxycodone', 'Topical Lidocaine patches'],
  },
  {
    drugA: 'Fluoxetine',
    drugB: 'Phenelzine',
    genericA: 'fluoxetine',
    genericB: 'phenelzine sulfate',
    severity: 'CONTRAINDICATED',
    mechanism: 'Synergistic excessive accumulation of synaptic serotonin due to combined MAO enzyme inhibition and SSRI reuptake blockade.',
    clinicalEffect: 'Fatal Serotonin Toxicity, malignant hyperpyrexia, cardiovascular collapse, autonomic storm.',
    management: 'Strictly contraindicated. Must observe a 5-week washout period after stopping fluoxetine before initiating any MAOI.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Cognitive behavioral therapy', 'Non-MAOI antidepressants after full washout'],
  },
  {
    drugA: 'Citalopram',
    drugB: 'Ondansetron',
    genericA: 'citalopram hydrobromide',
    genericB: 'ondansetron',
    severity: 'MAJOR',
    mechanism: 'Additive dose-dependent prolongation of the cardiac QTc interval and blockade of hERG potassium channels.',
    clinicalEffect: 'Torsades de Pointes (TdP), polymorphic ventricular tachycardia, syncope, sudden cardiac death.',
    management: 'Limit citalopram to max 20 mg/day in elderly. Perform baseline ECG and correct hypokalemia/hypomagnesemia.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Metoclopramide or Prochlorperazine for nausea', 'Sertraline for depression (lower QTc liability)'],
  },
  {
    drugA: 'Lithium',
    drugB: 'Ibuprofen',
    genericA: 'lithium carbonate',
    genericB: 'ibuprofen',
    severity: 'MAJOR',
    mechanism: 'NSAIDs inhibit renal prostaglandin synthesis, reducing renal blood flow and decreasing renal tubular excretion of lithium.',
    clinicalEffect: 'Lithium toxicity: ataxia, coarse tremors, dysarthria, hyperreflexia, seizures, irreversible neurotoxicity.',
    management: 'Avoid NSAIDs in patients on lithium. Use Acetaminophen/Paracetamol or topical analgesics. Check serum lithium levels if NSAID taken.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Acetaminophen / Paracetamol', 'Topical Diclofenac (with monitoring)', 'Capsaicin cream'],
  },
  {
    drugA: 'Lithium',
    drugB: 'Hydrochlorothiazide',
    genericA: 'lithium carbonate',
    genericB: 'hydrochlorothiazide',
    severity: 'MAJOR',
    mechanism: 'Thiazide diuretics cause sodium depletion in the distal tubule, prompting compensatory proximal tubular reabsorption of lithium.',
    clinicalEffect: '30% to 50% increase in serum lithium concentrations, acute lithium intoxication.',
    management: 'Reduce lithium dosage by 50% upon starting thiazide; monitor lithium levels within 3 to 5 days.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Loop diuretics (furosemide has less lithium interaction)', 'Calcium channel blockers for hypertension'],
  },
  {
    drugA: 'Alprazolam',
    drugB: 'Ketoconazole',
    genericA: 'alprazolam',
    genericB: 'ketoconazole',
    severity: 'CONTRAINDICATED',
    mechanism: 'Potent CYP3A4 inhibition by ketoconazole reduces alprazolam hepatic oxidative clearance by over 80%.',
    clinicalEffect: 'Profound central nervous system depression, respiratory arrest, coma, prolonged psychomotor impairment.',
    management: 'Avoid combination. Use Lorazepam or Oxazepam (glucuronidated, independent of CYP3A4).',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Lorazepam', 'Oxazepam', 'Temazepam'],
  },
  {
    drugA: 'Oxycodone',
    drugB: 'Diazepam',
    genericA: 'oxycodone hydrochloride',
    genericB: 'diazepam',
    severity: 'MAJOR',
    mechanism: 'Additive pharmacodynamic CNS and respiratory depression mediated by concurrent mu-opioid and GABA-A receptor activation.',
    clinicalEffect: 'Severe sedation, respiratory depression, anoxic brain injury, fatal overdose.',
    management: 'FDA Black Box Warning: Limit dosages and durations to minimum required. Co-prescribe Naloxone rescue kit.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Non-opioid multimodal analgesia (Gabapentin/Pregabalin, Acetaminophen)', 'Buspirone for anxiety'],
  },

  // Antimicrobials & Anti-infectives
  {
    drugA: 'Methotrexate',
    drugB: 'Amoxicillin',
    genericA: 'methotrexate',
    genericB: 'amoxicillin',
    severity: 'MAJOR',
    mechanism: 'Penicillins compete for organic anion transporter (OAT1/OAT3) renal secretion pathways, decreasing renal tubular elimination of methotrexate.',
    clinicalEffect: 'Methotrexate toxicity: severe bone marrow suppression, pancytopenia, mucositis, hepatotoxicity.',
    management: 'Monitor complete blood counts (CBC) and serum methotrexate levels closely. Consider alternative antimicrobial class.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Macrolides (Azithromycin)', 'Cephalosporins (with monitoring)', 'Nitrofurantoin for UTI'],
  },
  {
    drugA: 'Levofloxacin',
    drugB: 'Prednisone',
    genericA: 'levofloxacin',
    genericB: 'prednisone',
    severity: 'MAJOR',
    mechanism: 'Combined matrix metalloproteinase induction and tenocyte apoptosis by fluoroquinolones and systemic corticosteroids.',
    clinicalEffect: 'Markedly increased incidence of severe tendinitis and Achilles tendon rupture, especially in patients >60 years.',
    management: 'Avoid fluoroquinolones in patients taking oral steroids unless no alternative exists. Advise immediate cessation if tendon pain occurs.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Cephalosporins (Ceftriaxone, Cefuroxime)', 'Beta-lactams with beta-lactamase inhibitors', 'Doxycycline'],
  },
  {
    drugA: 'Linezolid',
    drugB: 'Sertraline',
    genericA: 'linezolid',
    genericB: 'sertraline',
    severity: 'CONTRAINDICATED',
    mechanism: 'Linezolid is a reversible, non-selective Monoamine Oxidase Inhibitor (MAOI) that blocks central serotonin breakdown.',
    clinicalEffect: 'Precipitation of severe Serotonin Syndrome, hyperthermia, seizures, mortality.',
    management: 'Contraindicated unless urgent MRSA/VRE treatment requires it. Discontinue SSRI immediately and monitor for serotonin toxicity.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Vancomycin', 'Daptomycin', 'Ceftaroline'],
  },
  {
    drugA: 'Metronidazole',
    drugB: 'Alcohol',
    genericA: 'metronidazole',
    genericB: 'ethanol',
    severity: 'MAJOR',
    mechanism: 'Metronidazole inhibits aldehyde dehydrogenase, causing toxic accumulation of acetaldehyde following alcohol ingestion.',
    clinicalEffect: 'Disulfiram-like reaction: flushing, throbbing headache, diaphoresis, nausea, vomiting, palpitations, hypotension.',
    management: 'Patients must abstain from alcohol and propylene glycol-containing products during therapy and for 72 hours after completion.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Tinidazole (still avoid alcohol)', 'Oral Vancomycin for C. difficile'],
  },

  // Endocrine & Metabolic
  {
    drugA: 'Metformin',
    drugB: 'Iodinated Contrast Media',
    genericA: 'metformin hydrochloride',
    genericB: 'iohexol / iopamidol',
    severity: 'MAJOR',
    mechanism: 'Contrast-induced nephropathy leads to acute renal impairment and subsequent systemic accumulation of metformin.',
    clinicalEffect: 'Severe Metformin-Associated Lactic Acidosis (MALA), high mortality rate (~50%).',
    management: 'Withhold metformin at time of or prior to iodinated radiocontrast procedure in patients with eGFR <60 mL/min. Re-evaluate renal function 48h post-procedure before resuming.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Non-contrast imaging modalities (MRI, Ultrasound)', 'Hydration protocols prior to contrast'],
  },
  {
    drugA: 'Levothyroxine',
    drugB: 'Calcium Carbonate',
    genericA: 'levothyroxine sodium',
    genericB: 'calcium carbonate',
    severity: 'MODERATE',
    mechanism: 'Calcium ions bind to levothyroxine in the acidic gastrointestinal tract, forming an insoluble non-absorbable chelate complex.',
    clinicalEffect: 'Decreased absorption of thyroid hormone by up to 30-40%, leading to subclinical or overt hypothyroidism and elevated TSH.',
    management: 'Separate administration times by at least 4 hours. Take levothyroxine in the morning fasting with water.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Separate dosing interval by 4 hours', 'Calcium Citrate (still requires separation)'],
  },
  {
    drugA: 'Levothyroxine',
    drugB: 'Ferrous Sulfate',
    genericA: 'levothyroxine sodium',
    genericB: 'ferrous sulfate',
    severity: 'MODERATE',
    mechanism: 'Iron cations chelate with levothyroxine, significantly impairing gastrointestinal mucosal absorption.',
    clinicalEffect: 'Persistent hypothyroidism despite dose escalation, fluctuating thyroid function tests.',
    management: 'Administer iron supplements at least 4 hours apart from levothyroxine.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Administer levothyroxine at 06:00 AM on empty stomach and iron supplements with dinner at 06:00 PM'],
  },
  {
    drugA: 'Glimepiride',
    drugB: 'Sulfamethoxazole-Trimethoprim',
    genericA: 'glimepiride',
    genericB: 'sulfamethoxazole/trimethoprim',
    severity: 'MAJOR',
    mechanism: 'Sulfamethoxazole inhibits CYP2C9 and displaces sulfonylureas from plasma protein binding sites.',
    clinicalEffect: 'Severe prolonged refractory hypoglycemia, neuroglycopenic symptoms, loss of consciousness.',
    management: 'Reduce sulfonylurea dose by 50% or substitute antibiotic. Instruct frequent capillary blood glucose checks.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Nitrofurantoin', 'Fosfomycin', 'Cephalexin for uncomplicated UTI'],
  },

  // Gastrointestinal & Renal
  {
    drugA: 'Methotrexate',
    drugB: 'Ibuprofen',
    genericA: 'methotrexate',
    genericB: 'ibuprofen',
    severity: 'MAJOR',
    mechanism: 'NSAIDs decrease renal prostaglandin synthesis and compete for renal tubular secretion, markedly reducing methotrexate excretion.',
    clinicalEffect: 'Severe bone marrow suppression, leukopenia, thrombocytopenia, acute kidney injury.',
    management: 'Avoid NSAIDs, especially with high-dose methotrexate regimens. If pain control is required, use acetaminophen or paracetamol.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Acetaminophen', 'Low-dose corticosteroids under rheumatology supervision'],
  },
  {
    drugA: 'Allopurinol',
    drugB: 'Azathioprine',
    genericA: 'allopurinol',
    genericB: 'azathioprine',
    severity: 'CONTRAINDICATED',
    mechanism: 'Allopurinol is a potent xanthine oxidase inhibitor, which is the primary metabolic inactivation pathway for 6-mercaptopurine (active metabolite of azathioprine).',
    clinicalEffect: 'Massive accumulation of active cytotoxic metabolites resulting in lethal bone marrow aplasia, severe leukopenia, sepsis.',
    management: 'If combination cannot be avoided, reduce azathioprine dose to 25-33% of standard dose and monitor weekly CBC.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Febuxostat (still has interaction, requires same dose reduction)', 'Uricosurics (Probenecid) if normal renal function', 'Rasburicase'],
  },
  {
    drugA: 'Spironolactone',
    drugB: 'Potassium Chloride',
    genericA: 'spironolactone',
    genericB: 'potassium chloride',
    severity: 'MAJOR',
    mechanism: 'Additive retention and exogenous supplementation of potassium.',
    clinicalEffect: 'Life-threatening hyperkalemia, cardiac arrest, tall peaked T-waves, PR prolongation.',
    management: 'Discontinue oral potassium supplements when starting potassium-sparing diuretics unless severe hypokalemia is documented with frequent lab monitoring.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Dietary management of electrolytes under medical supervision'],
  },
  {
    drugA: 'Theophylline',
    drugB: 'Ciprofloxacin',
    genericA: 'theophylline',
    genericB: 'ciprofloxacin',
    severity: 'MAJOR',
    mechanism: 'Ciprofloxacin potently inhibits hepatic CYP1A2, which metabolizes approximately 90% of theophylline.',
    clinicalEffect: 'Theophylline toxicity: intractable vomiting, cardiac arrhythmias, seizures, hypotension.',
    management: 'Reduce theophylline dose by 50% and obtain serum theophylline concentrations. Consider alternative antibiotic.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Levofloxacin (minimal CYP1A2 inhibition)', 'Azithromycin', 'Ceftriaxone'],
  },
  {
    drugA: 'Sildenafil',
    drugB: 'Nitroglycerin',
    genericA: 'sildenafil citrate',
    genericB: 'nitroglycerin / glyceryl trinitrate',
    severity: 'CONTRAINDICATED',
    mechanism: 'Synergistic nitric oxide / cyclic GMP vasodilation. PDE-5 inhibition prevents cGMP breakdown while nitrates stimulate cGMP production.',
    clinicalEffect: 'Profound refractory systemic hypotension, coronary hypoperfusion, acute myocardial infarction, cardiovascular collapse.',
    management: 'Absolute contraindication. Nitrates should not be administered within 24 hours of sildenafil/vardenafil or within 48 hours of tadalafil.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Beta-blockers, Calcium Channel Blockers, or Ranolazine for chronic stable angina'],
  },
  {
    drugA: 'Tadalafil',
    drugB: 'Isosorbide Mononitrate',
    genericA: 'tadalafil',
    genericB: 'isosorbide mononitrate',
    severity: 'CONTRAINDICATED',
    mechanism: 'Exaggerated cGMP-mediated vascular smooth muscle relaxation and precipitous drop in preload and blood pressure.',
    clinicalEffect: 'Severe syncope, profound shock, coronary and cerebral ischemia.',
    management: 'Do not prescribe nitrates to patients taking regular or as-needed tadalafil.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Alternative non-nitrate anti-anginal medications'],
  },
  {
    drugA: 'Tacrolimus',
    drugB: 'Voriconazole',
    genericA: 'tacrolimus',
    genericB: 'voriconazole',
    severity: 'MAJOR',
    mechanism: 'Voriconazole is a strong CYP3A4 inhibitor, decreasing tacrolimus first-pass and systemic clearance.',
    clinicalEffect: 'Markedly elevated tacrolimus trough levels, nephrotoxicity, neurotoxicity, posterior reversible encephalopathy syndrome (PRES).',
    management: 'Reduce tacrolimus dose to one-third of the original dose upon initiating voriconazole. Monitor daily whole blood tacrolimus trough levels.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Echinocandins (Caspofungin, Micafungin) which do not inhibit CYP3A4'],
  },
  {
    drugA: 'Cyclosporine',
    drugB: 'St. Johns Wort',
    genericA: 'cyclosporine',
    genericB: 'Hypericum perforatum',
    severity: 'MAJOR',
    mechanism: 'St. John\'s Wort is a potent inducer of CYP3A4 and P-glycoprotein, dramatically accelerating cyclosporine clearance.',
    clinicalEffect: 'Subtherapeutic cyclosporine blood concentrations, acute allograft rejection, transplant organ failure.',
    management: 'Avoid St. John\'s Wort in all solid organ transplant recipients.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Standard psychopharmacotherapy with close therapeutic drug monitoring (TDM)'],
  },
  {
    drugA: 'Carbamazepine',
    drugB: 'Oral Contraceptives',
    genericA: 'carbamazepine',
    genericB: 'ethinyl estradiol / levonorgestrel',
    severity: 'MAJOR',
    mechanism: 'Carbamazepine induces hepatic CYP3A4 enzymes and increases sex hormone-binding globulin, accelerating estrogen/progestin breakdown.',
    clinicalEffect: 'Contraceptive failure, unplanned breakthrough pregnancy, irregular bleeding.',
    management: 'Advise non-hormonal barrier contraception or non-CYP-interacting intrauterine devices (Copper IUD or Levonorgestrel 52mg IUD).',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Copper IUD', 'Levonorgestrel intrauterine system (IUS)', 'Barrier methods'],
  },
  {
    drugA: 'Phenytoin',
    drugB: 'Valproic Acid',
    genericA: 'phenytoin sodium',
    genericB: 'valproate sodium / divalproex',
    severity: 'MAJOR',
    mechanism: 'Valproic acid displaces phenytoin from albumin binding sites and inhibits its hepatic metabolism.',
    clinicalEffect: 'Elevated free (unbound) phenytoin levels causing ataxia, nystagmus, lethargy, despite normal total phenytoin lab readings.',
    management: 'Measure free unbound phenytoin levels and adjust dosage based on clinical response.',
    evidenceLevel: 'ESTABLISHED',
    alternatives: ['Levetiracetam', 'Lamotrigine (with slow titration)'],
  },
];
