import { ICD10Entry } from './types';

export const ICD10_CM_DATA: ICD10Entry[] = [
  // Chapter 9: Diseases of the Circulatory System (I00-I99)
  { code: 'I10', description: 'Essential (primary) hypertension', category: 'Hypertensive diseases', chapter: 'Circulatory', isBillable: true },
  { code: 'I11.0', description: 'Hypertensive heart disease with heart failure', category: 'Hypertensive diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I11.9', description: 'Hypertensive heart disease without heart failure', category: 'Hypertensive diseases', chapter: 'Circulatory', isBillable: true },
  { code: 'I12.0', description: 'Hypertensive chronic kidney disease with stage 5 chronic kidney disease or end stage renal disease', category: 'Hypertensive diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 136' },
  { code: 'I12.9', description: 'Hypertensive chronic kidney disease with stage 1 through stage 4 chronic kidney disease, or unspecified', category: 'Hypertensive diseases', chapter: 'Circulatory', isBillable: true },
  { code: 'I20.0', description: 'Unstable angina', category: 'Ischemic heart diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 87' },
  { code: 'I20.9', description: 'Angina pectoris, unspecified', category: 'Ischemic heart diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 88' },
  { code: 'I21.0', description: 'ST elevation (STEMI) myocardial infarction involving anterior wall', category: 'Acute myocardial infarction', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 86' },
  { code: 'I21.1', description: 'ST elevation (STEMI) myocardial infarction involving inferior wall', category: 'Acute myocardial infarction', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 86' },
  { code: 'I21.4', description: 'Non-ST elevation (NSTEMI) myocardial infarction', category: 'Acute myocardial infarction', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 86' },
  { code: 'I25.10', description: 'Atherosclerotic heart disease of native coronary artery without angina pectoris', category: 'Chronic ischemic heart disease', chapter: 'Circulatory', isBillable: true },
  { code: 'I25.110', description: 'Atherosclerotic heart disease of native coronary artery with unstable angina pectoris', category: 'Chronic ischemic heart disease', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 87' },
  { code: 'I48.0', description: 'Paroxysmal atrial fibrillation', category: 'Atrial fibrillation and flutter', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 96' },
  { code: 'I48.1', description: 'Persistent atrial fibrillation', category: 'Atrial fibrillation and flutter', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 96' },
  { code: 'I48.2', description: 'Chronic / Permanent atrial fibrillation', category: 'Atrial fibrillation and flutter', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 96' },
  { code: 'I50.20', description: 'Unspecified systolic (congestive) heart failure', category: 'Heart failure', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I50.21', description: 'Acute systolic (congestive) heart failure', category: 'Heart failure', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I50.22', description: 'Chronic systolic (congestive) heart failure (HFrEF)', category: 'Heart failure', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I50.30', description: 'Unspecified diastolic (congestive) heart failure (HFpEF)', category: 'Heart failure', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I50.32', description: 'Chronic diastolic (congestive) heart failure', category: 'Heart failure', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 85' },
  { code: 'I63.9', description: 'Cerebral infarction, unspecified (Ischemic Stroke)', category: 'Cerebrovascular diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 100' },
  { code: 'I73.9', description: 'Peripheral vascular disease, unspecified', category: 'Arterial diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 108' },
  { code: 'I82.401', description: 'Acute embolism and thrombosis of unspecified deep veins of right lower extremity (DVT)', category: 'Vein diseases', chapter: 'Circulatory', isBillable: true, hccCategory: 'HCC 107' },

  // Chapter 4: Endocrine, Nutritional and Metabolic Diseases (E00-E89)
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 19' },
  { code: 'E11.21', description: 'Type 2 diabetes mellitus with diabetic nephropathy', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 18' },
  { code: 'E11.22', description: 'Type 2 diabetes mellitus with diabetic chronic kidney disease', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 18' },
  { code: 'E11.319', description: 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 18' },
  { code: 'E11.40', description: 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 18' },
  { code: 'E11.51', description: 'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 18' },
  { code: 'E11.65', description: 'Type 2 diabetes mellitus with hyperglycemia', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 19' },
  { code: 'E10.9', description: 'Type 1 diabetes mellitus without complications', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 19' },
  { code: 'E10.65', description: 'Type 1 diabetes mellitus with hyperglycemia', category: 'Diabetes mellitus', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 19' },
  { code: 'E03.9', description: 'Hypothyroidism, unspecified', category: 'Thyroid disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E05.90', description: 'Thyrotoxicosis without mention of goiter or other cause', category: 'Thyroid disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E78.00', description: 'Pure hypercholesterolemia, unspecified', category: 'Metabolic disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E78.2', description: 'Mixed hyperlipidemia', category: 'Metabolic disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E66.01', description: 'Morbid (severe) obesity due to excess calories (BMI >= 40)', category: 'Nutritional disorders', chapter: 'Endocrine', isBillable: true, hccCategory: 'HCC 22' },
  { code: 'E66.9', description: 'Obesity, unspecified', category: 'Nutritional disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E87.1', description: 'Hypo-osmolality and hyponatremia', category: 'Fluid and electrolyte disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E87.5', description: 'Hyperkalemia', category: 'Fluid and electrolyte disorders', chapter: 'Endocrine', isBillable: true },
  { code: 'E87.6', description: 'Hypokalemia', category: 'Fluid and electrolyte disorders', chapter: 'Endocrine', isBillable: true },

  // Chapter 10: Diseases of the Respiratory System (J00-J99)
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified', category: 'Acute respiratory infections', chapter: 'Respiratory', isBillable: true },
  { code: 'J18.9', description: 'Pneumonia, unspecified organism', category: 'Pneumonia', chapter: 'Respiratory', isBillable: true, hccCategory: 'HCC 114' },
  { code: 'J44.0', description: 'Chronic obstructive pulmonary disease with (acute) lower respiratory infection', category: 'Chronic lower respiratory diseases', chapter: 'Respiratory', isBillable: true, hccCategory: 'HCC 111' },
  { code: 'J44.1', description: 'Chronic obstructive pulmonary disease with (acute) exacerbation', category: 'Chronic lower respiratory diseases', chapter: 'Respiratory', isBillable: true, hccCategory: 'HCC 111' },
  { code: 'J44.9', description: 'Chronic obstructive pulmonary disease, unspecified', category: 'Chronic lower respiratory diseases', chapter: 'Respiratory', isBillable: true, hccCategory: 'HCC 111' },
  { code: 'J45.20', description: 'Mild intermittent asthma, uncomplicated', category: 'Asthma', chapter: 'Respiratory', isBillable: true },
  { code: 'J45.40', description: 'Moderate persistent asthma, uncomplicated', category: 'Asthma', chapter: 'Respiratory', isBillable: true },
  { code: 'J45.50', description: 'Severe persistent asthma, uncomplicated', category: 'Asthma', chapter: 'Respiratory', isBillable: true },
  { code: 'J45.901', description: 'Unspecified asthma with (acute) exacerbation', category: 'Asthma', chapter: 'Respiratory', isBillable: true },
  { code: 'J96.00', description: 'Acute respiratory failure, unspecified whether with hypoxia or hypercapnia', category: 'Respiratory failure', chapter: 'Respiratory', isBillable: true, hccCategory: 'HCC 84' },

  // Chapter 14: Diseases of the Genitourinary System (N00-N99)
  { code: 'N17.9', description: 'Acute kidney failure, unspecified', category: 'Renal failure', chapter: 'Genitourinary', isBillable: true, hccCategory: 'HCC 135' },
  { code: 'N18.1', description: 'Chronic kidney disease, stage 1', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true },
  { code: 'N18.2', description: 'Chronic kidney disease, stage 2 (mild)', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true },
  { code: 'N18.30', description: 'Chronic kidney disease, stage 3 unspecified', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true },
  { code: 'N18.31', description: 'Chronic kidney disease, stage 3a', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true },
  { code: 'N18.32', description: 'Chronic kidney disease, stage 3b', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true },
  { code: 'N18.4', description: 'Chronic kidney disease, stage 4 (severe)', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true, hccCategory: 'HCC 137' },
  { code: 'N18.5', description: 'Chronic kidney disease, stage 5 (End stage)', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true, hccCategory: 'HCC 136' },
  { code: 'N18.6', description: 'End stage renal disease (ESRD on dialysis)', category: 'Chronic kidney disease', chapter: 'Genitourinary', isBillable: true, hccCategory: 'HCC 134' },
  { code: 'N39.0', description: 'Urinary tract infection, site not specified', category: 'Urinary system disorders', chapter: 'Genitourinary', isBillable: true },
  { code: 'N40.0', description: 'Benign prostatic hyperplasia without lower urinary tract symptoms', category: 'Male genital disorders', chapter: 'Genitourinary', isBillable: true },

  // Chapter 5: Mental, Behavioral and Neurodevelopmental Disorders (F01-F99)
  { code: 'F32.0', description: 'Major depressive disorder, single episode, mild', category: 'Mood disorders', chapter: 'Mental Health', isBillable: true },
  { code: 'F32.1', description: 'Major depressive disorder, single episode, moderate', category: 'Mood disorders', chapter: 'Mental Health', isBillable: true },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified', category: 'Mood disorders', chapter: 'Mental Health', isBillable: true, hccCategory: 'HCC 59' },
  { code: 'F33.1', description: 'Major depressive disorder, recurrent, moderate', category: 'Mood disorders', chapter: 'Mental Health', isBillable: true, hccCategory: 'HCC 59' },
  { code: 'F41.1', description: 'Generalized anxiety disorder', category: 'Anxiety disorders', chapter: 'Mental Health', isBillable: true },
  { code: 'F41.9', description: 'Anxiety disorder, unspecified', category: 'Anxiety disorders', chapter: 'Mental Health', isBillable: true },
  { code: 'F10.20', description: 'Alcohol dependence, uncomplicated', category: 'Substance use disorders', chapter: 'Mental Health', isBillable: true, hccCategory: 'HCC 55' },
  { code: 'F17.200', description: 'Nicotine dependence, cigarettes, uncomplicated', category: 'Substance use disorders', chapter: 'Mental Health', isBillable: true },

  // Chapter 13: Diseases of the Musculoskeletal System (M00-M99)
  { code: 'M17.11', description: 'Primary osteoarthritis, right knee', category: 'Osteoarthritis', chapter: 'Musculoskeletal', isBillable: true },
  { code: 'M17.12', description: 'Primary osteoarthritis, left knee', category: 'Osteoarthritis', chapter: 'Musculoskeletal', isBillable: true },
  { code: 'M54.50', description: 'Low back pain, unspecified', category: 'Dorsopathies', chapter: 'Musculoskeletal', isBillable: true },
  { code: 'M79.7', description: 'Fibromyalgia', category: 'Soft tissue disorders', chapter: 'Musculoskeletal', isBillable: true },
  { code: 'M81.0', description: 'Age-related osteoporosis without current pathological fracture', category: 'Bone disorders', chapter: 'Musculoskeletal', isBillable: true },
];
